export const demoUsers = {
  Student: {
    name: 'Demo Student',
    account: 'student.demo',
    initials: 'DS',
    subtitle: 'Graduate student · Fictional profile',
  },
  Advisor: {
    name: 'Demo Advisor',
    account: 'advisor.demo',
    initials: 'DA',
    subtitle: 'Manager · Career Services',
  },
  Administrator: {
    name: 'Demo Administrator',
    account: 'admin.demo',
    initials: 'AD',
    subtitle: 'VP · Student Affairs',
  },
}

export const initialEvents = [
  {
    id: 1,
    day: '18',
    month: 'AUG',
    title: 'Fall Welcome Mixer',
    category: 'Campus Life',
    location: 'Innovation Hall Atrium',
    time: '5:30–7:30 PM',
    attending: 126,
    capacity: 160,
    accent: 'violet',
    description: 'Meet student organizations, advisors, and new classmates over snacks and music.',
  },
  {
    id: 2,
    day: '20',
    month: 'AUG',
    title: 'AI Product Management Lab',
    category: 'Academic',
    location: 'Tech Center · Room 204',
    time: '2:00–4:00 PM',
    attending: 42,
    capacity: 48,
    accent: 'blue',
    description: 'A hands-on workshop for turning stakeholder needs into testable AI product outcomes.',
  },
  {
    id: 3,
    day: '22',
    month: 'AUG',
    title: 'Career Launch: Bay Area Tech',
    category: 'Career',
    location: 'Career Commons',
    time: '4:00–5:30 PM',
    attending: 78,
    capacity: 100,
    accent: 'orange',
    description: 'Recruiters and alumni share practical strategies for internships and early-career roles.',
  },
  {
    id: 4,
    day: '25',
    month: 'AUG',
    title: 'International Student Q&A',
    category: 'Student Support',
    location: 'Student Success Center',
    time: '12:00–1:00 PM',
    attending: 31,
    capacity: 60,
    accent: 'green',
    description: 'Get answers about campus resources, maintaining status, and academic planning.',
  },
  {
    id: 5,
    day: '28',
    month: 'AUG',
    title: 'Entrepreneurship Pitch Night',
    category: 'Innovation',
    location: 'BlueSky Auditorium',
    time: '6:00–8:00 PM',
    attending: 114,
    capacity: 180,
    accent: 'pink',
    description: 'Student founders pitch new ventures to faculty, peers, and local operators.',
  },
  {
    id: 6,
    day: '03',
    month: 'SEP',
    title: 'Mindful Monday Pop-up',
    category: 'Wellness',
    location: 'North Quad',
    time: '10:30–11:15 AM',
    attending: 18,
    capacity: 40,
    accent: 'teal',
    description: 'A short guided reset with the Counseling and Wellness team.',
  },
]

export const initialCourses = [
  {
    id: 'MB668',
    title: 'Project Management with AI',
    instructor: 'MB668 Faculty',
    schedule: 'Tue · 6:00–8:40 PM',
    location: 'Innovation Hall 302',
    credits: 3,
    enrolled: 24,
    capacity: 28,
    status: 'enrolled',
    color: 'violet',
  },
  {
    id: 'MB654',
    title: 'Investment & Portfolio Management',
    instructor: 'Finance Faculty',
    schedule: 'Thu · 6:00–8:40 PM',
    location: 'Business Center 118',
    credits: 3,
    enrolled: 30,
    capacity: 30,
    status: 'waitlisted',
    waitlistPosition: 3,
    color: 'blue',
  },
  {
    id: 'MB672',
    title: 'Digital Transformation Strategy',
    instructor: 'Strategy Faculty',
    schedule: 'Mon · 3:00–5:40 PM',
    location: 'Tech Center 210',
    credits: 3,
    enrolled: 19,
    capacity: 26,
    status: 'available',
    color: 'green',
  },
  {
    id: 'MB680',
    title: 'Entrepreneurial Leadership',
    instructor: 'Leadership Faculty',
    schedule: 'Wed · 6:00–8:40 PM',
    location: 'Business Center 204',
    credits: 3,
    enrolled: 22,
    capacity: 24,
    status: 'available',
    color: 'orange',
  },
  {
    id: 'CS610',
    title: 'Applied Generative AI',
    instructor: 'AI Faculty',
    schedule: 'Fri · 2:00–4:40 PM',
    location: 'AI Lab 1',
    credits: 3,
    enrolled: 36,
    capacity: 36,
    status: 'available',
    color: 'pink',
  },
]

export const advisors = [
  {
    id: 'emily',
    name: 'Career Services Advisor',
    role: 'Career Services',
    initials: 'CA',
    next: 'Tomorrow',
    color: 'violet',
  },
  {
    id: 'daniel',
    name: 'Academic Advisor',
    role: 'Academic Advising',
    initials: 'AA',
    next: 'Aug 15',
    color: 'blue',
  },
  {
    id: 'aisha',
    name: 'International Support Advisor',
    role: 'International Student Services',
    initials: 'IA',
    next: 'Aug 17',
    color: 'green',
  },
]

export const policyDocs = [
  {
    id: 'REG-2026-04',
    topic: 'Course registration',
    title: 'Registration & Add/Drop Policy',
    updated: 'July 18, 2026',
    keywords: ['register', 'registration', 'course', 'add', 'drop', 'deadline', 'class', 'enroll'],
    answer:
      'Students may add an open course through CampusConnect until 11:59 PM on the seventh calendar day of the term. Drops made during the first seven days do not appear on the transcript. After that date, advisor approval is required.',
  },
  {
    id: 'REG-2026-07',
    topic: 'Waitlists',
    title: 'Automated Waitlist Procedure',
    updated: 'July 22, 2026',
    keywords: ['waitlist', 'wait', 'full', 'seat', 'position', 'queue', 'notification'],
    answer:
      'When a seat opens, the first eligible student receives a BTU email and a 24-hour enrollment window. If the offer expires, the seat moves to the next student. Position is visible in Course Selection.',
  },
  {
    id: 'FERPA-2026-02',
    topic: 'Privacy & FERPA',
    title: 'Student Records and FERPA Standard',
    updated: 'June 30, 2026',
    keywords: ['ferpa', 'privacy', 'record', 'parent', 'share', 'data', 'resume', 'consent', 'directory'],
    answer:
      'BTU limits access to education records to staff with a legitimate educational interest. Student records, including resumes, are not released to third parties without documented consent unless a FERPA exception applies.',
  },
  {
    id: 'ADV-2026-03',
    topic: 'Appointments',
    title: 'Student Services Appointment Standard',
    updated: 'July 2, 2026',
    keywords: ['appointment', 'advisor', 'cancel', 'reschedule', 'career', 'meeting', 'book'],
    answer:
      'Students can book or reschedule an advising appointment up to two hours before the start time. Cancellations should be made in CampusConnect so the slot can be released to another student.',
  },
  {
    id: 'EVT-2026-01',
    topic: 'Campus events',
    title: 'Event Registration and Attendance Guide',
    updated: 'May 12, 2026',
    keywords: ['event', 'rsvp', 'ticket', 'attendance', 'capacity', 'cancel'],
    answer:
      'Campus events are free unless a fee is shown. An RSVP reserves one place. If plans change, cancel the RSVP at least 12 hours before the event so another student can attend.',
  },
  {
    id: 'AI-2026-01',
    topic: 'Responsible AI',
    title: 'Campus AI Assistant Use Standard',
    updated: 'August 1, 2026',
    keywords: ['ai', 'assistant', 'hallucination', 'answer', 'source', 'policy', 'accurate'],
    answer:
      'The CampusConnect assistant must ground policy answers in approved BTU documents and display the source. When evidence is missing or uncertain, it must say so and route the student to the responsible office.',
  },
]

export const engagementSeries = [38, 44, 49, 46, 58, 63, 71, 76, 74, 82, 88, 91]

export const auditEvents = [
  { time: '10:42 AM', actor: 'Demo student role', action: 'Viewed own course schedule', result: 'Allowed', tone: 'success' },
  { time: '10:36 AM', actor: 'Demo advisor role', action: 'Opened appointment queue', result: 'Allowed', tone: 'success' },
  { time: '10:31 AM', actor: 'Student role', action: 'Requested admin analytics', result: 'Blocked', tone: 'warning' },
  { time: '10:18 AM', actor: 'System', action: 'Policy index integrity check', result: 'Passed', tone: 'success' },
]
